export enum SCREENS {
  HOME = 'HOME',
  AUTH = 'AUTH',
  TAB_NAVIGATOR = 'TABNAVIGATOR',
  MESS_SCREEN = 'MESS_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SETTINGS_SCREEN = 'SETTINGS_SCREEN',
  DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
  ROOMS_SCREEN = 'ROOMS_SCREEN',
  ROOM_SCREEN = 'ROOM_SCREEN',
}
